name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: electron-app-win
          path: ./artifacts/win

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: electron-app-mac
          path: ./artifacts/mac

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: electron-app-linux
          path: ./artifacts/linux

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/win/**/*
            ./artifacts/mac/**/*
            ./artifacts/linux/**/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
